### First priority:  applicaiton.properties
### Second priority: applicaiton.yml
### Third priority:  applicaiton.yamn
### Last priority:   default value of 8080 for server port

# server:
#   port: 9001
